package com.xlccc.dao;

import com.xlccc.dataobject.userPasswordDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface userPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    int insert(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    int insertSelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    userPasswordDO selectByPrimaryKey(Integer id);

    userPasswordDO selectByUserId(Integer UserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    int updateByPrimaryKeySelective(userPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Feb 03 23:16:00 CST 2020
     */
    int updateByPrimaryKey(userPasswordDO record);
}